#!/usr/bin/env node

// Benchmarks every model in supportedModels.json against the ground-truth
// dataset in testDataset.json. Run generateDataset.js first if the file
// doesn't exist yet.
//
// Usage:
//   OPENROUTER_API_KEY=<key> node testModels.js

const fs = require('fs');
const path = require('path');
const SECTIONS = require('./supportedModels.json');
const { fetchAndClean, extractRecipe } = require('./extract');
const { scoreAgainstDataset } = require('./scoring');
const { TEST_URLS } = require('./config');

const DATASET_PATH = path.join(__dirname, 'testDataset.json');
const API_KEY = process.env.OPENROUTER_API_KEY;

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  if (!API_KEY) {
    console.error('Error: OPENROUTER_API_KEY environment variable is required.');
    process.exit(1);
  }

  if (!fs.existsSync(DATASET_PATH)) {
    console.error('Error: testDataset.json not found.');
    console.error('Run generateDataset.js first to create the ground-truth dataset.');
    process.exit(1);
  }

  const dataset = JSON.parse(fs.readFileSync(DATASET_PATH, 'utf-8'));
  console.log(`Dataset: ${dataset.entries.length} URLs, generated by ${dataset.model} on ${dataset.generatedAt.slice(0, 10)}`);

  const allModels = SECTIONS.flatMap(s => s.groups.flatMap(g => g.models));
  console.log(`Testing ${allModels.length} models\n`);

  // Fetch and clean each test page once, shared across all models.
  console.log('Fetching test pages...');
  const cleanPages = await Promise.all(
    TEST_URLS.map(async (url) => {
      process.stdout.write(`  ${url.slice(0, 60)}... `);
      const content = await fetchAndClean(url);
      console.log('done');
      return content;
    })
  );

  const report = [];

  for (const section of SECTIONS) {
    console.log(`\n${section.heading}`);

    for (const group of section.groups) {
      console.log(`\n  ${group.label}`);

      for (const modelId of group.models) {
        console.log(`\n  ${modelId}`);
        const results = [];

        for (let i = 0; i < TEST_URLS.length; i++) {
          const url = TEST_URLS[i];
          const cleanContent = cleanPages[i];
          const groundTruth = dataset.entries.find(e => e.url === url)?.recipe;

          if (!groundTruth) {
            console.log(`    [${i + 1}/${TEST_URLS.length}] No dataset entry for ${url} — skipping`);
            continue;
          }

          process.stdout.write(`    [${i + 1}/${TEST_URLS.length}] ${url.slice(0, 55)}... `);

          try {
            const extracted = await extractRecipe(modelId, cleanContent, API_KEY);
            process.stdout.write('responded, scoring... ');
            const { scores, total, mistakes } = scoreAgainstDataset(extracted, groundTruth);
            console.log(`${total}/50`);
            results.push({ url, score: total, scores, mistakes });
          } catch (err) {
            console.log(`ERROR: ${err.message.slice(0, 80)}`);
            results.push({ url, score: 0, error: err.message });
          }
        }

        const totalScore = results.reduce((sum, r) => sum + (r.score ?? 0), 0);
        const maxScore = results.length * 50;
        const pct = maxScore > 0 ? Math.round((totalScore / maxScore) * 100) : 0;
        console.log(`  => ${totalScore}/${maxScore} (${pct}%)`);

        for (const r of results) {
          if (r.mistakes?.length) {
            console.log(`     Mistakes (${new URL(r.url).hostname}):`);
            r.mistakes.forEach(m => console.log(`       - ${m}`));
          }
        }

        report.push({ modelId, results, totalScore, maxScore, pct });
      }
    }
  }

  // ─── Summary table ──────────────────────────────────────────────────────────

  const col = 52;
  console.log('\n\n' + '='.repeat(col + 20));
  console.log('SUMMARY (sorted by score)');
  console.log('='.repeat(col + 20));
  console.log(`${'Model'.padEnd(col)} Score     %`);
  console.log('-'.repeat(col + 20));

  for (const { modelId, totalScore, maxScore, pct } of [...report].sort((a, b) => b.pct - a.pct)) {
    const bar = '█'.repeat(Math.round(pct / 10)).padEnd(10);
    console.log(`${modelId.padEnd(col)} ${String(totalScore).padStart(3)}/${maxScore}  ${bar} ${pct}%`);
  }
}

main().catch(err => {
  console.error(err.message);
  process.exit(1);
});
